Add solution of HW 1 files
Denis-Leo/2022-2-VK-EDU-FS-Frontend-D-Dzhulya pull request #1
Opened 2022-10-01 18:40 UTC by Denis-Leo

# Домашнее задание № 1

Прошу @martinkomitsky, @haseprogram или @vaganov-spb проверить его.

Что было сделано:

* написаны функции в файлах convertBytesToHuman.js, correctSentence.js, nonUniqueElements.js;
*написан тест в  convertBytesToHuman.test.js
*

2022-10-01 22:56 UTC, martinkomitsky requested changes
Нужно удалить из репозитория папку `node_modules`, а ее положить в `.gitignore`

2022-10-03 05:55 UTC, Denis-Leo commented
сделано:
- удалена папка node_modules
- помещена в .gitignore

2022-10-03 15:33 UTC, martinkomitsky commented on convertBytesToHuman.test.js
> +  // ...
а где решение?

2022-10-03 15:34 UTC, martinkomitsky requested changes
См. коммент

2022-10-05 19:08 UTC, Denis-Leo commented on convertBytesToHuman.test.js
> +  // ...
имеется ввиду добавить ещё дополнительные тесты ?
Добавил

2022-10-05 19:09 UTC, Denis-Leo commented
Добавлены дополнительные тесты

2022-10-10 18:41 UTC, martinkomitsky approved these changes

2022-10-10 18:41 UTC, merged

2022-10-10 18:41 UTC, martinkomitsky commented
12